name: Garena Link Checker 24/7

on:
  schedule:
    - cron: '*/5 * * * *'  # Har 5 minute me background me auto check
  workflow_dispatch:      # Manual testing ke liye button

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Link Checker
        run: python main.py

